<?php

namespace DemandeBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{

    public function countUnreadCol(){
        return $this->createQueryBuilder('d')
            ->select('COUNT(d)')
            ->where('d.readDemande = false')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function allDemandes(){
        return $this->createQueryBuilder('d')
            ->select('COUNT(d)')
            ->getQuery()
            ->getSingleScalarResult();
    }



}
