admin_homepage:
    path:     /index
    defaults: { _controller: AdminBundle:Default:template }


_admin_users:
    path:     /users
    defaults: { _controller: AdminBundle:Default:afficher }

_front:
    path:     /front
    defaults: { _controller: AdminBundle:Default:front }
