imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    templating: { engines: ['twig'] }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    transport:        gmail
    username:         belhadjali.seif@gmail.com
    password:         ultraS1920
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
