index_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

_reponse_bundle:
    resource: "@ReponseBundle/Resources/config/routing.yml"
    prefix:   /reponses


_demande_bundle:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /dashboard/demandes/

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /dashboard/users/


admin_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /dashboard/

reclamation_bundle:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation/


reclamation_bundle:
    resource: "@ReponseBundle/Resources/config/routing.yml"
    prefix:   /reclamation/reponses/


homepage:
    resource: "@ReponseBundle/Resources/config/routing.yml"
    prefix:   /reclamation/reponses/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"