devis:
    resource: "@DevisBundle/Resources/config/routing.yml"
    prefix:   /dashboard/devis/

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

index_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

_reponse_bundle:
    resource: "@ReponseBundle/Resources/config/routing.yml"
    prefix:   /dashboard/reponses




_demande_bundle:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /dashboard/demandes/

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /dashboard/users/


admin_bundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /dashboard/

reclamation_bundle:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /dashboard/reclamation/


reclamation_bundle:
    resource: "@ReponseBundle/Resources/config/routing.yml"
    prefix:   /dashboard/reclamation/reponses/


homepage:
    resource: "@ReponseBundle/Resources/config/routing.yml"
    prefix:   /reclamation/reponses/

app:
    resource: '@AppBundle/Controller/'
    type: annotation

_api_bundle:
    type:   rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


api_login_check:
    path: /api/login_check
    controller : AppBundle\Controller\DefaultController:index

_getQuote:
    path: /getQuote
    controller : AppBundle\Controller\DefaultController:quote

json_login:
    path:       /json_login
    controller: AppBundle\Controller\SecurityController::login
    methods: POST