security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_LIVREUR:      ROLE_LIVREUR
        ROLE_USER:        ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
                    pattern: ^/api/doc
                    security: false


        login:
                    pattern:  ^/api/login
                    stateless: true
                    anonymous: true
                    form_login:
                        check_path:               /api/login_check
                        username_parameter: username
                        password_parameter: password
                        success_handler:          lexik_jwt_authentication.handler.authentication_success
                        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                        require_previous_session: false


        api:
            pattern:   ^/api
            stateless: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path:    /dashboard/index
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

            logout:
                path:   /logout
                target: /login
            anonymous:    true
    access_control:
            - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }