security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_LIVREUR:      ROLE_LIVREUR
        ROLE_USER:        ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
                    pattern:  ^/api/login
                    stateless: true
                    form_login:
                        check_path:               /api/login_check
                        username_parameter: username
                        password_parameter: password
                        success_handler:          lexik_jwt_authentication.handler.authentication_success
                        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                        require_previous_session: false





        main:
            anonymous: ~
            pattern: ^/
            json_login:
                check_path: /json_login
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path:    /dashboard/index
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

            logout:
                path:   /logout
                target: /login
            anonymous:    true
    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/dashboard/users, role: ROLE_ADMIN }
