_list_demande:
    path:     /list
    defaults: { _controller: DemandeBundle:Default:list }

_create_demande:
    path:     /create
    defaults: { _controller: DemandeBundle:Default:create }

_create_demande_coursier:
    path:     /create-demande-coursier
    defaults: { _controller: DemandeBundle:Default:createDemandeCoursier }




_update_demande:
    path:     /update/{id}
    defaults: { _controller: DemandeBundle:Default:update }

_update_demande_coursier:
    path:     /update-demande-coursier/{id}
    defaults: { _controller: DemandeBundle:Default:updateDemandeCoursier }



_remove_demande:
    path:     /remove/{id}
    defaults: { _controller: DemandeBundle:Default:remove }

_remove_all_demande:
    path:     /removeAll
    defaults: { _controller: DemandeBundle:Default:removeAll }


_assign_demande:
    path:     /assign/{id_demande}
    defaults: { _controller: DemandeBundle:Default:affecter }

_archive_demande:
    path:     /archive/{id}
    defaults: { _controller: DemandeBundle:Default:archive }

_desarchive_demande:
    path:     /deasrchive/{id}
    defaults: { _controller: DemandeBundle:Default:desarchive }



_liste_archive_demande:
    path:     /listArchive
    defaults: { _controller: DemandeBundle:Default:listArchive }


confirm_demande:
    path:     /assign/{id_demande}/{id_livreur}
    defaults: { _controller: DemandeBundle:Default:confirmAssign }

_valide_demande:
    path:     /assign_final/{id_demande}
    defaults: { _controller: DemandeBundle:Default:valideDemande }

_generate_url:
    path:     /pdf/{id_demande}
    defaults: { _controller: DemandeBundle:Default:generatepdf }

view_pdf:
    path:     /view/{id_demande}
    defaults: { _controller: DemandeBundle:Default:viewPdf }


filterClients:
    path:     /filterClient
    defaults: { _controller: DemandeBundle:Default:filterClient }


filterClientsDate:
    path:     /filterClientDate
    defaults: { _controller: DemandeBundle:Default:filterClientDate }


filterGlobal:
    path:     /filterGlobal
    defaults: { _controller: DemandeBundle:Default:filterGlobal }

filterGlobalCoursier:
    path:     /filterGlobalCoursier
    defaults: { _controller: DemandeBundle:Default:filterGlobalCoursier }





filterGlobalLivreur:
    path:     /filterGlobalLivreur
    defaults: { _controller: DemandeBundle:Default:filterGlobalLivreur }




testthis:
    path:     /testthis
    defaults: { _controller: DemandeBundle:Default:testThis }




_seen_all_demande:
    path:     /seen
    defaults: { _controller: DemandeBundle:Default:seen }


_ajax_listt_demande:
    path:     /api/demandes/list
    defaults: { _controller: DemandeBundle:Default:ajaxList }



