_list_demande:
    path:     /list
    defaults: { _controller: DemandeBundle:Default:list }

_create_demande:
    path:     /create
    defaults: { _controller: DemandeBundle:Default:create }


_update_demande:
    path:     /update/{id}
    defaults: { _controller: DemandeBundle:Default:update }


_remove_demande:
    path:     /remove/{id}
    defaults: { _controller: DemandeBundle:Default:remove }


_assign_demande:
    path:     /assign/{id_demande}
    defaults: { _controller: DemandeBundle:Default:affecter }

confirm_demande:
    path:     /assign/{id_demande}/{id_livreur}
    defaults: { _controller: DemandeBundle:Default:confirmAssign }

_valide_demande:
    path:     /assign_final/{id_demande}
    defaults: { _controller: DemandeBundle:Default:valideDemande }

_generate_url:
    path:     /pdf
    defaults: { _controller: DemandeBundle:Default:generatepdf }

view_pdf:
    path:     /view
    defaults: { _controller: DemandeBundle:Default:viewPdf }



_seen_all_demande:
    path:     /seen
    defaults: { _controller: DemandeBundle:Default:seen }


