_list_users:
    path:     /list
    defaults: { _controller: UserBundle:Default:index }
_create_user:
    path:     /create
    defaults: { _controller: UserBundle:Default:create }

_update_user:
    path:     /update/{id}
    defaults: { _controller: UserBundle:Default:update }


_remove_user:
    path:     /remove/{id}
    defaults: { _controller: UserBundle:Default:remove }


_send_mail_to_user:
    path:     /send_to_user/{id}
    defaults: { _controller: UserBundle:Default:sendToUser }

_send_mail_to_admin:
    path:     /send_to_admin/{id}
    defaults: { _controller: UserBundle:Default:sendToAdmin }


_test_mail:
    path:     /test_mail/
    defaults: { _controller: UserBundle:Default:testMail }



